### ISSUE TITLE
Can't finish evaluation without an ETH address

### ISSUE THREAD

**Issue by thedarkjester** [jredondoh/blockchain-developer-bootcamp-final-project#2]
Please provide me with an Ethereum Address to mark the project against

**Comment by jredondoh** [comment]
I deployed both contracts in Goerli and put their addresses in the deployed_address.txt file. Is that you are referring to?

**Comment by thedarkjester** [comment]
This is your ethereum address for NFTs if we provided them for successful students.

**Comment by jredondoh** [comment]
0x4F44bf577b04b4f30EB948dbEd2e5337b69ccdc9
Thanks!!

**Comment by thedarkjester** [comment]
Hi, I since realised it was optional. Thanks for this though. I will put it against your project
